### ISSUE TITLE
Create all appropriate Lab and Challenge Issues

### ISSUE THREAD

**Issue by mfernest** [ramtindavanlou/Cloudera_bootcamp#12]
I can't properly evaluate the work submitted without Issues to track the results. Please create them according to the instructions in the lab and challenge notes.

I'm postponing evaluation until these Issues are created.

**Comment by ramtindavanlou** [comment]
Hi Mike - sure, I will create the issues soonest possible. This week, I am delivering a project so I am slammed but I'll do it in either after work or in the weekend.

**Comment by mfernest** [comment]
Understood.
