### ISSUE TITLE
ZooKeeper service does not start on one of the nodes

### ISSUE THREAD

**Issue by ramtindavanlou** [ramtindavanlou/Cloudera_bootcamp#3]
Moving the /var/lib/zookeeper directory from one of the good nodes to the bad node!

**Comment by mikeridley** [comment]
Yup!  The key is to make sure to change the id to something unique (preferably the id of the zookeeper that went down).  I know we just discussed this, but I'm writing it here for your reference later.

**Comment by ramtindavanlou** [comment]
Thanks. It worked!
