### ISSUE TITLE
Can't start NFS service on one on the nodes

### ISSUE THREAD

**Issue by ramtindavanlou** [ramtindavanlou/Cloudera_bootcamp#4]
I get this error when I try to start NFS on this node:
![image](https://cloud.githubusercontent.com/assets/11170285/18721268/ad2ba350-7ffd-11e6-9a13-ecbfa93b4724.png)

**Comment by mikeridley** [comment]
I haven't used the NFS gateway service role in ages, but the message indicates that portmap and rpcbind need to be running and that seems reasonable to me.  Try starting those services on the gateway node and see if it fixes the problem.  Might be worth filing a JIRA on our end, as I don't really know why we would force the user to do that manually, versus having Cloudera Manager handle it.
